services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  rabbitMQ:
    image: rabbitmq:4-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  python-server:
    build: .
    ports:
      - "8000:8000"